- name: first ansible play book 
  hosts: localhost 
  vars_files:
    - m.yaml
  vars_prompt:
    - name: mohan
      prompt: "enter your name"
      private: True 
  tasks:
  - name: displaying the the task 
    ansible.builtin.debug:
      msg: "this is the first number is {{name}} amd the age is {{age}} and salary is {{salary}} and {{mohan}}"