- name: first ansible play book 
  hosts: mongodb
  vars:
    packages:
      - nginx 
      - git 
      - ansible 
      - mysql 
    state: 
      - present 
      - present 
      - present
      - present 
  tasks: 
  - name: decsibing the all databases
    ansible.builtin.yum:
      name: "{{item.0}}"
      state: "{{item.1}}"
    with_together: 
      - "{{packages}}"
      - "{{state}}"
     
    

  