- name: first ansible play book 
  hosts: mongodb
  vars:
    names: [1,2,3,4,5,7]

  tasks: 
  - name: decsibing the all databases
    ansible.builtin.debug: 
      msg: "the list is {{}}"
    with_items:
      - "{{names}}"
   
     
    

  