- name: first ansible play book 
  hosts: mongodb
  vars:
    name: mohan 
    age: 25 
  vars_prompt:
    - name: salary 
      prompt: "please enter yur salary for future use"
      private: false

  tasks: 
  - name: decsibing the all databases
    become: yes
    ansible.builtin.yum:
      name: "{{item.0}}"
      state: "{{item.1}}"
    with_together: 
      - "{{packages}}"
      - "{{state}}"
     
    

  