- name: first ansible play book 
  hosts: localhost 
  vars:
    details:
      name: mohan 
      age : 30 
      salary: 4000 
      education: btech
  tasks: 
  - name: decsibing the all databases
    ansible.builtin.debug:
      msg: "my details are {{item.key}} and {{item.value}}"
    with_dict: "{{details}}"
    when: "item.salary > 10000"

  