- name: first ansible play book 
  hosts: localhost 
  vars_files::
    - m.yaml
  tasks:
  - name: displaying the the task 
    ansible.builtin.debug:
      msg: "this is the first number is {{name}} amd the age is {{age}} and salary is {{salary}}"