- name: first ansible play book 
  hosts: localhost 
  vars:
    num:
     - 1
     - 2
     - 3
     - 4
     - 5
  tasks:
  - name: selecting the even numbers 
    ansible.builtin.debug:
      msg: "even numbers are {{item}}"
    loop: "{{num | select('even')}}"
  