- name: first ansible play book 
  hosts: localhost 
  vars: 
    my_list:
      - mohan
      - chiru
      - vijay
      - praveen
  tasks:
  - name: displaying the the task 
    ansible.builtin.debug:
      msg: "this is the first number is {{num1}} and second number is {{num2}}"