- name: first ansible play book 
  hosts: localhost 
  vars:
    details:
      name: mohan 
      age : 30 
      salary: 4000 
      education: btech
    address:
      village: gangavaram 
      state: ap 
      dist: chittoor 
  tasks: 
  - name: decsibing the all databases
    ansible.builtin.debug:
      msg: "my details are {{item.0.key}}"
    with_dict: 
     - "{{details}}"
     - "{{address}}"
    

  